#!/usr/bin/env bash
#Bash script that will display information about subdomains

display_info ()
{
    dig_cmd=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | cut -f3- --output-delimiter=' ' | tr ' ' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $dig_cmd" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 1 ]; then
    display_info "$1" 'www'
    display_info "$1" 'lb-01'
    display_info "$1" 'web-01'
    display_info "$1" 'web-02'
else
    display_info "$1" "$2"
fi
